config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :groups
  
  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    validates :name, presence: true,
                    length: { minimum: 5 }
end

app/models/membership.rb
class Membership < ApplicationRecord
    validates :group_id, presence: true
    validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

    def index
        @groups = Group.all
    end

    def show
        @group = Group.find(params[:id])
    end

    def new
        @group = Group.new
    end

    def edit
        @group = Group.find(params[:id])
    end

    def create
        @group = Group.new(group_params)
        @user = session[:user_id]

        if @group.save
            @membership = Membership.new({user_id: @user, group_id: @group.id, is_admin: true, paid: false})
            @membership.save
            redirect_to groups_path
        else
            render 'new'
        end
    end

    def update
        @group = Group.find(params[:id])
       
        if @group.update(group_params)
          redirect_to groups_path
        else
          render 'edit'
        end
    end

    def destroy
        @group = Group.find(params[:id])

        Membership.all.each do |membership|
            if membership.group_id == @group.id
                membership.destroy
            end
        end
        
        @group.destroy
   
        redirect_to groups_path
    end

    private
        def group_params
            params.require(:group).permit(:name, :place, :date_time,
                                            :cost, :additional_detail)
        end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to groups_path, notice: 'Member was added.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to groups_path, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:is_admin, :paid, :user_id, :group_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_username(params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      session[:user_username] = @user.username
      redirect_to groups_path
    else
      flash.now[:alert] = "Invalid username or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    session[:user_username] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # format.html { redirect_to @user, notice: 'User was successfully created.' }
        # format.json { render :show, status: :created, location: @user }
        format.html { redirect_to new_session_path, notice: 'User was successfully created.' }
        # redirect_to memberships_path
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_with model: @group, local: true, class: 'form-box' do |form| %>
 
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@group.errors.count, "error") %> prohibited
          this group from being saved:
        </h2>
        <ul>
          <% @group.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name, class: 'input' %>
    </p>

    <p>
      <%= form.label :place %><br>
      <%= form.text_field :place, class: 'input' %>
    </p>

    <p>
      <%= form.label :dates_and_times %><br>
      <%= form.text_field :date_time, class: 'input' %>
    </p>

    <p>
      <%= form.label :cost %><br>
      <%= form.text_field :cost, class: 'input' %>
    </p>
   
    <p>
      <%= form.label :additional_detail %><br>
      <%= form.text_area :additional_detail, class: 'input' %>
    </p>
   
    <p>
      <%= form.submit 'Create Group', class: 'form-btn'%>
    </p>
   
  <% end %>

app/views/groups/edit.html.erb
<h1>Edit group</h1>
 
<%= render 'form'%>
 
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<%= render 'shared/header'%>

<h1>My groups</h1>

<div class="btn">
    <i class="fa fa-plus"> </i><%= link_to 'New group', new_group_path, class: "link" %>
</div>

<div class="box-container">

  <% count = 0 %>

  <% Membership.all.each do |membership| %>
    <% if membership.user_id == session[:user_id] %>
      <% group = Group.find_by_id(membership.group_id) %>
      <% count += 1 %>

      <div class="box">
        <h1><%= group.name %></h1>
        <div class="info">
          <div class="info-line">
            <i class="fa fa-map-marker"></i> <%= group.place %>
          </div>
          <div class="info-line">
            <i class="fa fa-calendar"></i> <%= group.date_time %>
          </div>
          <div class="info-line">
            <i class="fa fa-dollar"></i> <%= group.cost %>
          </div>
        </div>
        <p><%= group.additional_detail %></p>
        <%= link_to 'Info and actions', group_path(group) %>
      </div>
    <% end %>
  <% end %>

  <% if count == 0%>
    <p> You do not belong to any group yet. Create your own! </p>
  <% end %>
</div>

<div class="btn">
    <i class="fa fa-reply"></i>
    <%= link_to 'Log out', class: "link", controller: 'sessions', action: 'destroy' %>
</div>

app/views/groups/new.html.erb
<div class="container">
  <h1>New group!</h1>

  <%= render 'form'%>
  
  <%= link_to 'Back', groups_path %>
</div>

app/views/groups/show.html.erb
<%= render 'shared/header'%>

<h1><%= @group.name %></h1>
<div style="margin: 1rem">
  <div class="info">
    <div class="info-line">
      <i class="fa fa-map-marker"></i> <%= @group.place %>
    </div>
    <div class="info-line">
      <i class="fa fa-calendar"></i> <%= @group.date_time %>
    </div>
    <div class="info-line">
      <i class="fa fa-dollar"></i> <%= @group.cost %>
    </div>
  </div>
  <p><%= @group.additional_detail %></p>
</div>

<% admin = false %>
<% Membership.all.each do |membership| %>
  <% if membership.user_id == session[:user_id] and membership.group_id == @group.id and membership.is_admin%>
    <% admin = true %>
  <% end %>
<% end %>

<div class="players-list">


<div class="player">
  <div class="player-info">
    <div class="player-name">
      <h3>Name</h3>
    </div>
    <div class="player-admin">
      <h3>Administrator</h3>
    </div>
    <div class="player-paid">
      <h3>Monthly fees paid</h3>
    </div>
  </div>
  <div class="players-options">
    
  </div>
</div>

<% Membership.all.each do |membership| %>
  <% if membership.group_id == @group.id %>
    
    <div class="player">
      <div class="player-info">
        <div class="player-name">
          <%= User.find_by_id(membership.user_id).username %>
        </div>
        <div class="player-admin">
          <% if membership.is_admin %>
            yes
          <% else %>
            no
          <% end %>
        </div>
        <div class="player-paid">
          <% if membership.paid %>
            yes
          <% else %>
            no
          <% end %>
        </div>
      </div>
      <div class="players-options">
        <% if admin == true %>
          <%= link_to 'Edit', edit_membership_path(membership) %>
          <%= link_to 'Remove', membership, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>
</div>

<br>

<% if admin == true %>
  <div class="btn">
    <i class="fa fa-plus"> </i>
    <%= link_to 'Add member', new_membership_path(:group_ref => @group.id), class: "link" %>
  </div>
  <br><br>
  <%= link_to 'Edit info', edit_group_path(@group) %> |
  <%= link_to 'Delete', group_path(@group),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
  <br><br>
<% end %>

<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pedrinho</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memberships/_form.html.erb
<%= form_with(model: membership, local: true) do |form| %>
  <% if membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field hidden">
    <%= form.label :group_id %><br />
    <%= form.select :group_id, :value => group_ref %>
  </div>

  <div class="field">
    <%= form.label :user_id %><br />
    <% valid_users = [] %>
    <% User.all.each do |user| %>
      <% add = true %>
      <% Membership.all.each do |membership| %>
        <% if membership.group_id.to_i == group_ref.to_i and membership.user_id.to_i == user.id.to_i %>
          <% add = false %>
        <% end %>
      <% end %>
      <% if add %>
          <% valid_users.push(user) %>
      <% end %>
    <% end %>
    <% if valid_users.length > 0 %>
      <%= form.select :user_id, options_for_select(valid_users.map{|s|[s.username, s.id]}) %>
    <% else %>
      <p><strong>No users found to add!</strong></p>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :is_admin %>
    <%= form.check_box :is_admin %>
  </div>

  <div class="field">
    <%= form.label :paid %>
    <%= form.check_box :paid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<% user = User.find_by_id(@membership.user_id) %>
<% group = Group.find_by_id(@membership.group_id) %>

<h1>User <%=user.username%> in group <%=group.name%></h1>

<%= form_with(model: @membership, local: true) do |form| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :is_admin %>
    <%= form.check_box :is_admin %>
  </div>

  <div class="field">
    <%= form.label :paid %>
    <%= form.check_box :paid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', groups_path %>

app/views/memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memberships</h1>

<table>
  <thead>
    <tr>
      <th>User ID</th>
      <th>Group ID</th>
      <th>Is admin</th>
      <th>Paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.user_id %></td>
        <td><%= membership.group_id %></td>
        <td><%= membership.is_admin %></td>
        <td><%= membership.paid %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>Add member to <%= Group.find_by_id(params[:group_ref]).name %></h1>

<%= render 'form', membership: @membership, group_ref: params[:group_ref] %>

<%= link_to 'Back', groups_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Is admin:</strong>
  <%= @membership.is_admin %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @membership.paid %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>

app/views/shared/_header.html.erb
<div  class="header-container">
  <%= image_tag "avatar.png", class: "avatar" %>
  <h1><%= session[:user_username] %></h1>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, class: 'form-box') do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1><%= title %></h1>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: 'input' %>
  </div>

  <div class="actions">
    <%= form.submit 'Sign Up', class: 'form-btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container">
  <h1 class="teste">PEDRINHO</h1>
  <%= image_tag "logo.png" %>
  <h3>FOOTBALL GROUPS ADMINISTRATION</h3>
  <%= render 'form', user: @user, title: 'New User' %>
  <%= link_to 'Back', login_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>